"""books_table

Revision ID: 32fc6b26f194
Revises: 
Create Date: 2019-05-20 21:35:28.357777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32fc6b26f194'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booksection',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=64), nullable=True),
    sa.Column('section_path', sa.String(length=128), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.add_column('books', sa.Column('author', sa.String(length=32), nullable=True))
    op.drop_column('books', 'autor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('autor', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('books', 'author')
    op.drop_table('booksection')
    # ### end Alembic commands ###
